# "Vagrant 설정 형식 버전 2를 사용한다는 의미"
Vagrant.configure("2") do |config|

  # 이미지 정보
  config.vm.box = "ubuntu/focal64"
  #-> "Box(VM Image)를 Ubuntu/focal64를 사용하겠다는 의미로, Vagrant Cloud로부터 가져온다."
  
  config.vm.box_version = "20211026.0.0"
  #-> "Box(VM Image) 이미지의 버전 정보"
  
  config.vm.hostname = "testvm"
  #-> "호스트 이름 지정"
  
  config.vm.network "private_network", ip: "172.168.111.10"
  #config.vm.network "public_network", ip: "192.168.50.10"
  #-> "네트워크 설정"
  
  config.vm.network "forwarded_port", guest: 22, host: 60510, auto_correct: true, id: "ssh"
  #-> "네트워크 설정 - Guest의 Port와 Host의 Port를 매핑"
  #-> "auto_correct: 만약 Host의 Port가 이미 사용중이라면 자동으로 다른 미사용 Port를 할당"
  
  config.vm.synced_folder "./", "/vagrant", disabled: true
  #-> "공유 폴더 설정 - 첫 번째 파라미터(Host 디렉토리), 두 번째 파라미터(Guest 디렉토리)"
  #-> "disabled: true - 공유 폴더를 사용하지 않을 경우 true를 설정"
  
  # Virtualbox의 가상 머신 설정
  config.vm.provider "virtualbox" do |spec|
    #-> 메모리, cpu, 가상머신이름 지정
    spec.memory = "2048"
    spec.cpus = "2"
    spec.name = "testvm"
  end
end
   