# "An Improved Way to use YAML with Vagrant"

# Require YAML module
require 'yaml'

# Read YAML file with box details
vm_spec = YAML.load_file(File.join(File.dirname(__FILE__), 'config.yml'))

# OS & Version
linux_os = "ubuntu/focal64"
linux_version = "20220608.0.0"

Vagrant.configure("2") do |config|
  vm_spec.each do |spec|
    config.vm.define spec["name"] do |cfg|
      cfg.vm.box = linux_os
      cfg.vm.box_version = linux_version
      cfg.vm.network "public_network", ip: spec["ip"]
      cfg.vm.hostname = spec["name"]

      cfg.vm.provider "virtualbox" do |vb|
        vb.memory = spec["memory"]
        vb.cpus = spec["cpu"]
        vb.name = spec["name"]
      end
    end
  end
end